In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
import statistics as st

# Libraries For Text

import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('punkt')
nltk.download('stopwords')



from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import confusion_matrix
%matplotlib inline

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
# Read csv file

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Udemy ds course datasets/loan_small.csv')
df

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,NaN
4,LP001008,Male,NaN,0.0,141.0,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
6,LP001013,Male,2333.0,1516.0,NaN,rural,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
12,LP001028,Female,NaN,8106.0,NaN,urban,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y

In [ ]:
# Access the data frame using iloc

In [ ]:
subset = df.iloc[0:3,1:3] #note: [(row_range),(col_range)]
subset

  Gender  ApplicantIncome
0    NaN           5849.0
1   Male           4583.0
2   Male           3000.0

In [ ]:
# access the data using column name

In [ ]:
subsetN = df[['Gender','ApplicantIncome']][0:3] # note: [[specific colun]][row/index]
subsetN

  Gender  ApplicantIncome
0    NaN           5849.0
1   Male           4583.0
2   Male           3000.0

In [ ]:
# Read TSV  file

In [ ]:
datasetT = pd.read_csv('/content/drive/MyDrive/Udemy ds course datasets/loan_small_tsv.txt' , sep = '\t')
datasetT

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,Y
4,LP001008,Male,NaN,0.0,141.0,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
6,LP001013,Male,2333.0,1516.0,NaN,semi,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
12,LP001028,Female,NaN,8106.0,NaN,NaN,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
15,LP001032,NaN,4950.0,0.0,125.0,semi,Y

In [ ]:
# Function of pandas

# Head

In [ ]:
datasetT.head(10)

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,Y
4,LP001008,Male,NaN,0.0,141.0,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
6,LP001013,Male,2333.0,1516.0,NaN,semi,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N

# Shape

In [ ]:
datasetT.shape

(16, 7)

# Column Names

In [ ]:
datasetT.columns

Index(['Loan_ID', 'Gender', 'ApplicantIncome', 'CoapplicantIncome',
       'LoanAmount', 'Area', 'Loan_Status'],
      dtype='object')

# Find out missing columns

In [ ]:
datasetT.isna().sum(axis=0)

Loan_ID              0
Gender               2
ApplicantIncome      2
CoapplicantIncome    1
LoanAmount           3
Area                 2
Loan_Status          0
dtype: int64

In [ ]:
# Data pre-processing by removing null entries

# Clean Data

In [ ]:
cleandata = datasetT.dropna()
cleandata

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
3,LP001006,Female,2583.0,2358.0,120.0,semi,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y

# Remove nan from one specific column

In [ ]:
cleandata = datasetT.dropna(subset =['LoanAmount'])
cleandata

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,Y
4,LP001008,Male,NaN,0.0,141.0,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
15,LP001032,NaN,4950.0,0.0,125.0,semi,Y

In [ ]:
dt = datasetT.copy()
dt.columns

Index(['Loan_ID', 'Gender', 'ApplicantIncome', 'CoapplicantIncome',
       'LoanAmount', 'Area', 'Loan_Status'],
      dtype='object')

In [ ]:
cols = ['Gender','Area', 'Loan_Status']

dt[cols] = dt[cols].fillna(dt.mode().iloc[0])

In [ ]:
dt.isna().sum()

Loan_ID              0
Gender               0
ApplicantIncome      2
CoapplicantIncome    1
LoanAmount           3
Area                 0
Loan_Status          0
dtype: int64

# Remove numerical values

In [ ]:
col2 = ['ApplicantIncome','CoapplicantIncome','LoanAmount']

dt[col2] = dt[col2].fillna(dt[col2].mean()) # note: to fill with mean we have to give 'column_name' with dataset inside'fillna'

dt.isna().sum()

Loan_ID              0
Gender               0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Area                 0
Loan_Status          0
dtype: int64

# Label Encoding

In [ ]:
# Change object data types to 'category'

In [ ]:
dt.dtypes

Loan_ID               object
Gender                object
ApplicantIncome      float64
CoapplicantIncome    float64
LoanAmount           float64
Area                  object
Loan_Status           object
dtype: object

In [ ]:
dt[cols] = dt[cols].astype('category')

In [ ]:
dt.dtypes

Loan_ID                object
Gender               category
ApplicantIncome       float64
CoapplicantIncome     float64
LoanAmount            float64
Area                 category
Loan_Status          category
dtype: object

In [ ]:
for c in cols:
  dt[c] = dt[c].cat.codes

In [ ]:
dt

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,1,5849.000000,0.000000,140.923077,2,1
1,LP001003,1,4583.000000,2509.333333,128.000000,1,0
2,LP001005,1,3000.000000,0.000000,66.000000,1,1
3,LP001006,0,2583.000000,2358.000000,120.000000,1,1
4,LP001008,1,4103.571429,0.000000,141.000000,2,1
5,LP001011,1,5417.000000,4196.000000,267.000000,1,1
6,LP001013,1,2333.000000,1516.000000,140.923077,1,1
7,LP001014,0,3036.000000,2504.000000,158.000000,1,0
8,LP001018,1,4006.000000,1526.000000,168.000000,0,1
9,LP001020,1,12841.000000,10968.000000,349.000000,1,0
10,LP001024,0,3200.000000,700.000000,70.000000,2,1
11,LP001027,1,2500.000000,1840.000000,109.000000,2,1
12,LP001028,0,4103.571429,8106.000000,140.923077,1,1
13,LP001029,1,1853.000000,2840.000000,114.000000,2,0
14,LP001030,1,1299.000000,1086.000000,17.000000,1,1
15,LP001032,1,4950.000000,0.000000,125.000000,1,1

# Hot Encoding

In [ ]:
df2 = df.copy()
df

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,NaN
4,LP001008,Male,NaN,0.0,141.0,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
6,LP001013,Male,2333.0,1516.0,NaN,rural,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
12,LP001028,Female,NaN,8106.0,NaN,urban,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y

In [ ]:
df2 = df2.drop(['Loan_ID'], axis=1)
df2

    Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area Loan_Status
0      NaN           5849.0                0.0         NaN  urban           Y
1     Male           4583.0                NaN       128.0   semi           N
2     Male           3000.0                0.0        66.0    NaN           Y
3   Female           2583.0             2358.0       120.0   semi         NaN
4     Male              NaN                0.0       141.0  urban           Y
5     Male           5417.0             4196.0       267.0   semi           Y
6     Male           2333.0             1516.0         NaN  rural           Y
7   Female           3036.0             2504.0       158.0   semi           N
8     Male           4006.0             1526.0       168.0  rural           Y
9     Male          12841.0            10968.0       349.0   semi           N
10  Female           3200.0              700.0        70.0  urban           Y
11    Male           2500.0             1840.0       109.0  urban           Y
12  Female              NaN             8106.0         NaN  urban           Y
13    Male           1853.0             2840.0       114.0  urban           N
14    Male           1299.0             1086.0        17.0   semi           Y
15    Male           4950.0                0.0       125.0   semi           Y

In [ ]:
df2 = pd.get_dummies(df2 )

In [ ]:
col_names = ['Gender_Female'	,'Gender_Male'	,'Area_rural'	,'Area_semi'	,'Area_urban',	'Loan_Status_N',	'Loan_Status_Y']

In [ ]:
df2[col_names] = df2[col_names].astype(int)

In [ ]:
df2

,ApplicantIncome,CoapplicantIncome,LoanAmount,Gender_Female,Gender_Male,Area_rural,Area_semi,Area_urban,Loan_Status_N,Loan_Status_Y
0,5849.0,0.0,NaN,0,0,0,0,1,0,1
1,4583.0,NaN,128.0,0,1,0,1,0,1,0
2,3000.0,0.0,66.0,0,1,0,0,0,0,1
3,2583.0,2358.0,120.0,1,0,0,1,0,0,0
4,NaN,0.0,141.0,0,1,0,0,1,0,1
5,5417.0,4196.0,267.0,0,1,0,1,0,0,1
6,2333.0,1516.0,NaN,0,1,1,0,0,0,1
7,3036.0,2504.0,158.0,1,0,0,1,0,1,0
8,4006.0,1526.0,168.0,0,1,1,0,0,0,1
9,12841.0,10968.0,349.0,0,1,0,1,0,1,0
10,3200.0,700.0,70.0,1,0,0,0,1,0,1
11,2500.0,1840.0,109.0,0,1,0,0,1,0,1
12,NaN,8106.0,NaN,1,0,0,0,1,0,1
13,1853.0,2840.0,114.0,0,1,0,0,1,1,0
14,1299.0,1086.0,17.0,0,1,0,1,0,0,1
15,4950.0,0.0,125.0,0,1,0,1,0,0,1

# Data Normalization

In [ ]:
dt = df.copy()

In [ ]:
dt = dt.dropna()

In [ ]:
dt

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y

In [ ]:
dt = dt.drop(['Loan_ID','Gender','Area'	,'Loan_Status'],axis = 1)
dt

    ApplicantIncome  CoapplicantIncome  LoanAmount
5            5417.0             4196.0       267.0
7            3036.0             2504.0       158.0
8            4006.0             1526.0       168.0
9           12841.0            10968.0       349.0
10           3200.0              700.0        70.0
11           2500.0             1840.0       109.0
13           1853.0             2840.0       114.0
14           1299.0             1086.0        17.0
15           4950.0                0.0       125.0

In [ ]:
# Import stander scaler

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler_ = StandardScaler()

ss_values = scaler_.fit_transform(dt)
ss_values

array([[ 0.32879835,  0.43390231,  1.1995349 ],
       [-0.40126276, -0.11198867,  0.05261118],
       [-0.10384182, -0.4275214 ,  0.15783354],
       [ 2.60514177,  2.61875676,  2.06235824],
       [-0.35097716, -0.69401428, -0.87334558],
       [-0.56561083, -0.32621539, -0.46297838],
       [-0.76399367, -0.00358478, -0.4103672 ],
       [-0.9338609 , -0.56947886, -1.43102409],
       [ 0.18560703, -0.9198557 , -0.29462261]])

In [ ]:
# import minmax scaler

In [ ]:
from sklearn.preprocessing import minmax_scale

In [ ]:
mm_scaler = minmax_scale(dt)

In [ ]:
mm_scaler

array([[0.35678392, 0.38256747, 0.75301205],
       [0.15049385, 0.22830051, 0.4246988 ],
       [0.23453474, 0.13913202, 0.45481928],
       [1.        , 1.        , 1.        ],
       [0.16470282, 0.06382203, 0.15963855],
       [0.10405476, 0.16776076, 0.27710843],
       [0.04799861, 0.25893508, 0.29216867],
       [0.        , 0.09901532, 0.        ],
       [0.31632299, 0.        , 0.3253012 ]])